config/routes.rb
Rails.application.routes.draw do

  root 'homes#home'
  get "/help",to: 'homes#help'
  get "/contact",to: 'homes#contact'
  get "/about",to: 'homes#about'

  get "/signup",to: "users#new"
 post "/signup",to: "users#create" 

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :name , presence: true, length:{maximum:50}
    # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email , presence: true, length:{maximum:255}
    # format: { with: VALID_EMAIL_REGEX }
    # uniqueness: { case_sensitive: false }
    # has_secure_password
    # validates :password, presence: true, length:{minimum:6}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    # debugger
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:succes] = "Welcome tutorial"
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        raise "#{@user.errors.full_messages}"
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email,:password,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = "")
        base_title = "tutorial"
        if page_title.empty?
            base_title
        else 
            page_title + " | " + base_title
        end
    end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
      end
end

app/views/homes/about.html.erb
<% provide(:title ,"about")%>
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/contact.html.erb
<% provide(:title ,"contact")%>
<h1>Homes#contact</h1>
<p>Find me in app/views/homes/contact.html.erb</p>

app/views/homes/help.html.erb
<% provide(:title ,"help")%>
<h1>Homes#help</h1>
<p>Find me in app/views/homes/help.html.erb</p>

app/views/homes/home.html.erb
<div class="center jumbotron">
    <h1><%= link_to "tutorial",root_path %></h1>
    <p>Find me in app/views/homes/home.html.erb</p>

    <%= link_to "sign up", signup_path ,class:"btn btn-info btn-lg"%>
    <%= link_to image_tag("IMG_3098.jpg",alt: "tutorial", :size => "50x50"),
        "http://rubyonrails.org/" %>
</div>

app/views/layouts/_footer.html.erb
<footer>
    <nav>
        <ul>
            <li><%= link_to "help",help_path %></li>
            <li><%= link_to "contact",contact_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <%= link_to "tutorial", root_path %>
            <nav class="nav navbar-nav navbar-right">
                <ul>
                    <li><%= link_to "home",root_path %></li>
                    <li><%= link_to "about",about_path %></li>
                    <li><%= link_to "log in", "#" %></li>
                </ul>
            </nav>
    </div>
</header>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
<%= render "layouts/rails_default" %>
  </head>

  <body>
  <%= render "layouts/header"%>
  <div class="container">
    <%= yield %>
    <%= render "layouts/footer"%>
    <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>

app/views/layouts/rails_default.html.erb
<head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: user, local: true, url:signup_path) do |form| %>
    <%= render "shared/error_messages"%>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name , class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email , class: 'form-control' %>
    </div>
    
    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password , class: 'form-control'  %>
    </div>

    <div class="field">
      <%= form.label :password_confirmation ,"confirmation"%>
      <%= form.password_field :password_confirmation , class: 'form-control' %>
    </div>

    <div class="actions">
      <%= form.submit "Create My account" , class:"btn btn-info" %>
    </div>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title ,"signup")%>
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% provide(:title,"@user.name")%>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= gravatar_for @user %>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>